version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: https://github.com/wurstmeister/kafka-docker.git#a88b071fe48446abeb685c6a13b5496f1654c2f8
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/broker
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  connect:
    build: .
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock